[PHP]
variables_order = EGPCS
memory_limit = 2048M
max_execution_time = 600
max_input_time = 600
post_max_size = 512M
upload_max_filesize = 512M
max_allowed_packet = 512M
serialize_precision = -1
max_input_vars=20000
