#!/usr/bin/env bash

service nginx start
service php7.4-fpm start

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
