name: modulos-cengicana

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/modulos-app/Dockerfile
    container_name: modulos-cengicana-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8085:80"
    environment:
      TZ: America/Guatemala
