services:
    app:
        build:
            context: ./
            dockerfile: dockerfiles/app/Dockerfile
        restart: always
        ports:
            - "80:80"
        depends_on:
            - mysql
            - redis
        environment:
            - "TZ=America/Guatemala"
    mysql:
        build:
            context: ./
            dockerfile: dockerfiles/mysql/mysql.docker
        volumes:
            - "sigec-mysql-data:/var/lib/mysql"
        restart: always
        environment:
            - "TZ=America/Guatemala"
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=sigec
        ports:
            - "3306:3306"
    redis:
        build:
            context: ./
            dockerfile: dockerfiles/redis/redis.docker
        restart: always
volumes:
    sigec-mysql-data:
